[package]
name = "vban-mini"
version = "0.2.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
portaudio = "*"
ringbuffer = "*"
byteorder = "*"
clap = { version = "4.1.11", features = ["derive"] }
